// src/lib/components/Countdown.svelte
<script lang="ts">
    import { onMount } from "svelte";

    let days = $state("00");
    let hours = $state("00");
    let minutes = $state("00");
    let seconds = $state("00");
    let isOver = $state(false);

    onMount(() => {
        const weddingDate = new Date("Mar 25, 2026 10:00:00").getTime();

        const updateTimer = () => {
            const now = new Date().getTime();
            const distance = weddingDate - now;

            if (distance < 0) {
                isOver = true;
                return;
            }

            days = Math.floor(distance / (1000 * 60 * 60 * 24))
                .toString()
                .padStart(2, "0");
            hours = Math.floor(
                (distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60),
            )
                .toString()
                .padStart(2, "0");
            minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60))
                .toString()
                .padStart(2, "0");
            seconds = Math.floor((distance % (1000 * 60)) / 1000)
                .toString()
                .padStart(2, "0");
        };

        updateTimer();
        const interval = setInterval(updateTimer, 1000);

        return () => clearInterval(interval);
    });
</script>

<section id="countdown" class="py-20 px-[5%] bg-[#efebe9] text-center">
    <div class="max-w-[800px] mx-auto reveal">
        <h2 class="font-heading text-[2.5rem] text-[#5d4037] mb-12">
            The Celebration Begins In
        </h2>

        {#if isOver}
            <h3 class="font-heading text-3xl text-[#8d6e63]">
                The Celebration Has Begun!
            </h3>
        {:else}
            <div class="flex justify-center flex-wrap gap-8 max-md:gap-4">
                <div
                    class="bg-white w-[100px] h-[100px] max-md:w-[80px] max-md:h-[80px] flex flex-col justify-center items-center rounded-xl shadow-[0_5px_15px_rgba(0,0,0,0.05)]"
                >
                    <span
                        class="text-[2.5rem] max-md:text-[1.8rem] font-semibold text-[#5d4037] font-heading"
                        >{days}</span
                    >
                    <p
                        class="text-sm max-md:text-xs uppercase tracking-[1px] text-[#8d6e63]"
                    >
                        Days
                    </p>
                </div>
                <div
                    class="bg-white w-[100px] h-[100px] max-md:w-[80px] max-md:h-[80px] flex flex-col justify-center items-center rounded-xl shadow-[0_5px_15px_rgba(0,0,0,0.05)]"
                >
                    <span
                        class="text-[2.5rem] max-md:text-[1.8rem] font-semibold text-[#5d4037] font-heading"
                        >{hours}</span
                    >
                    <p
                        class="text-sm max-md:text-xs uppercase tracking-[1px] text-[#8d6e63]"
                    >
                        Hours
                    </p>
                </div>
                <div
                    class="bg-white w-[100px] h-[100px] max-md:w-[80px] max-md:h-[80px] flex flex-col justify-center items-center rounded-xl shadow-[0_5px_15px_rgba(0,0,0,0.05)]"
                >
                    <span
                        class="text-[2.5rem] max-md:text-[1.8rem] font-semibold text-[#5d4037] font-heading"
                        >{minutes}</span
                    >
                    <p
                        class="text-sm max-md:text-xs uppercase tracking-[1px] text-[#8d6e63]"
                    >
                        Minutes
                    </p>
                </div>
                <div
                    class="bg-white w-[100px] h-[100px] max-md:w-[80px] max-md:h-[80px] flex flex-col justify-center items-center rounded-xl shadow-[0_5px_15px_rgba(0,0,0,0.05)]"
                >
                    <span
                        class="text-[2.5rem] max-md:text-[1.8rem] font-semibold text-[#5d4037] font-heading"
                        >{seconds}</span
                    >
                    <p
                        class="text-sm max-md:text-xs uppercase tracking-[1px] text-[#8d6e63]"
                    >
                        Seconds
                    </p>
                </div>
            </div>
        {/if}
    </div>
</section>

// src/app/components/Countdown.tsx
import { useState, useEffect } from "react";
import { differenceInSeconds } from "date-fns";
import { motion } from "motion/react";

interface TimeLeft {
  days: number;
  hours: number;
  minutes: number;
  seconds: number;
}

const Countdown = () => {
  const targetDate = new Date("2026-03-25T10:00:00");
  const [timeLeft, setTimeLeft] = useState<TimeLeft>({ days: 0, hours: 0, minutes: 0, seconds: 0 });

  useEffect(() => {
    const interval = setInterval(() => {
      const now = new Date();
      const secondsDiff = differenceInSeconds(targetDate, now);

      if (secondsDiff <= 0) {
        clearInterval(interval);
        setTimeLeft({ days: 0, hours: 0, minutes: 0, seconds: 0 });
        return;
      }

      const days = Math.floor(secondsDiff / (3600 * 24));
      const hours = Math.floor((secondsDiff % (3600 * 24)) / 3600);
      const minutes = Math.floor((secondsDiff % 3600) / 60);
      const seconds = secondsDiff % 60;

      setTimeLeft({ days, hours, minutes, seconds });
    }, 1000);

    return () => clearInterval(interval);
  }, [targetDate]);

  return (
    <div className="flex flex-col items-center justify-center py-12 px-4 text-rose-900">
      <h2 className="text-3xl md:text-4xl font-serif mb-8 text-center">We are getting married in...</h2>
      <div className="flex flex-wrap justify-center gap-4 md:gap-8">
        <TimeUnit value={timeLeft.days} label="Days" />
        <TimeUnit value={timeLeft.hours} label="Hours" />
        <TimeUnit value={timeLeft.minutes} label="Minutes" />
        <TimeUnit value={timeLeft.seconds} label="Seconds" />
      </div>
    </div>
  );
};

const TimeUnit = ({ value, label }: { value: number; label: string }) => (
  <motion.div 
    initial={{ opacity: 0, y: 20 }}
    animate={{ opacity: 1, y: 0 }}
    className="flex flex-col items-center bg-white/60 backdrop-blur-sm rounded-lg p-4 min-w-[100px] shadow-sm border border-rose-100"
  >
    <span className="text-4xl md:text-5xl font-bold text-rose-800">{String(value).padStart(2, '0')}</span>
    <span className="text-sm uppercase tracking-wider text-rose-600 mt-2">{label}</span>
  </motion.div>
);

export default Countdown;
