// src/app/components/Footer.tsx
import { Instagram } from "lucide-react";

const Footer = () => {
  return (
    <footer className="w-full bg-rose-50/80 backdrop-blur-sm py-12 text-center text-rose-800 relative z-10">
      <div className="flex flex-col items-center justify-center gap-4">
        <p className="font-serif text-lg tracking-wide">For more wedding related updates</p>
        <a 
          href="https://www.instagram.com/sunraysandpoetry" 
          target="_blank" 
          rel="noopener noreferrer"
          className="flex items-center gap-2 px-6 py-3 bg-white hover:bg-rose-100 rounded-full shadow-sm border border-rose-200 transition-colors duration-300 font-medium"
        >
          <Instagram className="w-5 h-5" />
          <span>@sunraysandpoetry</span>
        </a>
        <p className="mt-8 text-xs text-rose-400 uppercase tracking-widest">
          Made with <span className="text-rose-600">❤️</span> by Kavitha & SUraj
        </p>
      </div>
    </footer>
  );
};

export default Footer;

// src/lib/components/Footer.svelte
<script lang="ts">
</script>

<footer class="bg-[#3e2723] text-white text-center py-16 px-[5%]">
    <p class="opacity-70 mb-2 text-base">
        For detailed wedding itinerary visit:
    </p>
    <p class="mb-8">
        <a
            href="https://sunraysandpoetry.com"
            class="text-white text-[1.2rem] no-underline tracking-[1px] transition-colors duration-300 hover:text-[#d7ccc8]"
            >sunraysandpoetry.com</a
        >
    </p>

    <p class="font-heading text-4xl my-8 opacity-100">S &amp; K</p>

    <p class="text-sm mt-8 opacity-70">Designed with ❤️</p>
</footer>
